version: '3'

services:

    wordpress:
        container_name: wp
        image: arm32v7/wordpress
        volumes:
            -  ./wp_data:/var/www/html
        ports:
            - '80:80'
        environment:
          - WORDPRESS_DB_HOST=mysql
          - WORDPRESS_DB_USER=user
          - WORDPRESS_DB_PASSWORD=password
          - WORDPRESS_DB_NAME=wp 

    mysql:
        container_name: maria
        image: yobasystems/alpine-mariadb
        volumes:
            - ./bd_data:/var/lib/mysql'
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=wp
          - MYSQL_USER=user
          - MYSQL_PASSWORD=password
        expose:
          - "3306" 

    adminer:
        container_name: adm
        image: arm32v7/adminer    
        depends_on:      
          - mysql
        ports:      
          - "8080:8080"        
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - ADMINER_USERNAME=user
          - MYSQL_DATABASE=wp
          - ADMINER_PASSWORD=password    

volumes:
    bd_data: 
    wp_data: 



